name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop  
jobs:
  check-Application:
    runs-on: ubuntu-latest
    #strategy:
     # matrix:
      #  go: ['1.14','1.15']

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-go@v2
       with:
          go-version: 1.15
     - run: go test
     - run: go run math.go

     #Fazer Setup do Docker para funcionar em varias arquiteturas
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3

       #Fazer o build do Docker
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3


     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v5
       with:
          push: true
          tags: alekseidasilva/fc3.0-ci:latest

          #Ajustando Arquivo